# Generated by Django 5.1.6 on 2025-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario_name', models.CharField(max_length=50)),
                ('Usuario_Texto', models.CharField(max_length=200)),
                ('Usuario_Lingua_Para_Tradução', models.CharField(max_length=200)),
                ('Usuario_Tradução', models.CharField(max_length=200)),
            ],
        ),
    ]
