# Generated by Django 5.1.6 on 2025-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario_Lingua_Para_Tradução',
            new_name='Lingua_Para_Tradução',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario_Texto',
            new_name='Texto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario_Tradução',
            new_name='Tradução',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario_name',
            new_name='name',
        ),
    ]
